name: Prerelease

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - name: Dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Do Release
        run: |
          git config --global user.email "bot@noreply.lukasbach.com"
          git config --global user.name "lukasbachbot"
          npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          yarn lerna publish prerelease --yes --no-verify-access --summary-file --loglevel silly --dist-tag prerelease
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release info
        run: cat ./lerna-publish-summary.json
      - name: Update lockfile
        run: |
          echo "enableImmutableInstalls: false" > ./.yarnrc.yml
          yarn
          git checkout HEAD -- ./.yarnrc.yml
        env:
          CI: false
      - name: Push remaining changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: lukasbachbot
          author_email: bot@noreply.lukasbach.com
          message: 'chore: tidy up after prerelease'
